@host=http://localhost:5272

POST {{host}}/auth/register
Content-Type: application/json

{
    "phone": "0000009999",
    "password": "1Leduytuanvu",
    "rePassword": "1Leduytuanvu",
    "fullName": "LE DUY TUAN VU"
}