@host=http://localhost:5272

GET {{host}}/categories
Authorization: Bearer gyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYTMyMzA4Ny02ODU3LTRhM2UtOGIyMy00ZDg2NDFmNzgzOTQiLCJqdGkiOiI0YzYzOTQwOS1kOGYwLTRmMzktODc5Ny0yYzNjNThmZmJkOTQiLCJpYXQiOiIxMi8xNC8yMDIyIDk6MDg6MzIgQU0iLCJQaG9uZSI6IjAwMDk5OTk5OTkiLCJQYXNzd29yZCI6IjgzMjZDNEM3RDY3ODc3NENDNkE5QjVGODQ5OEM4NjUzMDNDMTk3OTMzOUU3OUI2OTg4MDM1QTI3ODYyMzQyRUQiLCJleHAiOjE2NzEwMTI1MTIsImlzcyI6IlRoYW9OaHVTaG9wSXNzdWVyIiwiYXVkIjoiVGhhb05odVNob3BBdWRpZW5jZSJ9.cf-OIh5sPj3q20RrWxo8gz_1LezadKaTBuXVVOZbHZI